spring.datasource.url=jdbc:postgresql://localhost:5432/contructordb
spring.datasource.username=userdb
spring.datasource.password=rE6x67J7rN3C
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.flyway.baselineOnMigrate=true
spring.flyway.validateOnMigrate=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


