INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (1, 'Acre', 'AC');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (2, 'Alagoas', 'AL');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (3, 'Amazonas', 'AM');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (4, 'Bahia', 'BA');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (5, 'Ceará', 'CE');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (6, 'Distrito Federal', 'DF');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (7, 'Espírito Santo', 'ES');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (8, 'Goiás', 'GO');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (9, 'Maranhão', 'MA');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (10, 'Mato Grosso', 'MT');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (11, 'Mato Grosso do Sul', 'MS');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (12, 'Minas Gerais', 'MG');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (13, 'Pará', 'PA');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (14, 'Paraíba', 'PB');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (15, 'Paraná', 'PR');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (16, 'Pernambuco', 'PE');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (17, 'Piauí', 'PI');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (18, 'Rio de Janeiro', 'RJ');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (19, 'Rio Grande do Norte', 'RN');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (20, 'Rio Grande do Sul', 'RS');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (21, 'Rondônia', 'RO');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (22, 'Roraima', 'RR');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (23, 'Santa Catarina', 'SC');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (24, 'São Paulo', 'SP');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (25, 'Sergipe', 'SE');
INSERT INTO state (st_id, st_name, st_abbreviation) VALUES (26, 'Tocantins', 'TO');
